# Generated by Django 3.1.2 on 2020-10-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progs', '0003_progs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='langname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
